### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by YiXuanZX** [hosizoraru/StarVoyager#11]
大佬，反馈一个bug。

更新3.1后，无论是否开启永不息屏功能，无论息屏时间是多少，手机都不会息屏，回退3.0后正常。

机型：红米K50

系统版本：MIUI 14.0.6.0.TLNCNXM

Magisk日志:https://wwye.lanzouk.com/ifslN12j51cb

LSPosed模块日志:https://wwye.lanzouk.com/iliSP12j518h

LSPosed详细日志:https://wwye.lanzouk.com/iCvMK12j51aj

**Comment by hosizoraru** [comment]
我没有找到有关我的模块的错误日志，对于mix4，即使打开这个功能，设置为15s是可以正常息屏的。没有息屏可能是你的错觉或者你开了注视感知什么的。更具体的表现你应该尝试录屏等反馈，而且我暂时没有遇到其他人反馈这个异常。
