### ISSUE TITLE
应用商店去启动广告打开后会影响浏览器

### ISSUE THREAD

**Issue by Mubai-meng** [hosizoraru/StarVoyager#13]
会影响浏览器下载一些偏门应用
如https://dudu-lucky.com/guide/update.html#%E5%98%9F%E5%98%9F%E6%A1%8C%E9%9D%A2pro

![Screenshot_2023-07-15-16-04-53-799_com.xiaomi.market.jpg](https://github.com/hosizoraru/StarVoyager/assets/86759349/15362a72-7bfe-4a77-bcc9-069b843c9838)

**Comment by hosizoraru** [comment]
我在砍的时候砍过头了，后续会修复

**Comment by hosizoraru** [comment]
> 会影响浏览器下载一些偏门应用 如https://dudu-lucky.com/guide/update.html#%E5%98%9F%E5%98%9F%E6%A1%8C%E9%9D%A2pro
> 
> ![Screenshot_2023-07-15-16-04-53-799_com.xiaomi.market.jpg](https://user-images.githubusercontent.com/86759349/253728665-15362a72-7bfe-4a77-bcc9-069b843c9838.jpg)

其实CI里面修了，你去github actions里面下载来试试看就好

**Comment by Mubai-meng** [comment]
> > 会影响浏览器下载一些偏门应用 如https://dudu-lucky.com/guide/update.html#%E5%98%9F%E5%98%9F%E6%A1%8C%E9%9D%A2pro
> > 
> > ![Screenshot_2023-07-15-16-04-53-799_com.xiaomi.market.jpg](https://user-images.githubusercontent.com/86759349/253728665-15362a72-7bfe-4a77-bcc9-069b843c9838.jpg)
> 
> 其实CI里面修了，你去github actions里面下载来试试看就好

好的👌🏻感谢
