### ISSUE TITLE
新版控制中心添加 磁贴列数修改

### ISSUE THREAD

**Issue by zkzmba793** [hosizoraru/StarVoyager#14]
大佬请问可以加一下chimi中的这个功能吗？在miui14，a13中这个功能还有效
![Screenshot_2023-08-01-14-20-15-335_chili xposed chimi-edit](https://github.com/hosizoraru/StarVoyager/assets/73212412/ae752c51-82f2-4589-ab54-23438e36dea5)
效果如图所示
![IMG_20230801_142920](https://github.com/hosizoraru/StarVoyager/assets/73212412/2138e5c6-027a-4093-9a2c-e14d851f159d)

**Comment by hosizoraru** [comment]
感觉大于4太挤了，小于4又没有必要，所以这个没必要写。
旧版控制中心的可以改，主要是新版的控制中心这里是固定大小就这么点磁贴排序，多了难看少了也难看。下面空空的位置小米也不适合得利用一下。
