### ISSUE TITLE
开关触发位置问题

### ISSUE THREAD

**Issue by hua-sky** [hosizoraru/StarVoyager#19]
建议所有开关触发位置在红色框框处，蓝色框框处不触发开关。原因：有时滑动屏幕就会打开一个开关，有点烦。
个人感受，仅仅建议。![IMG_20230830_112001.jpg](https://github.com/hosizoraru/StarVoyager/assets/78088386/27c3f66d-168d-4108-8ac5-4b75e9828003)

**Comment by Mubai-meng** [comment]
这个问题确实很难受

**Comment by smanlin** [comment]
確實經常遇到

**Comment by hosizoraru** [comment]
CI已经同步上游修复改善了
