### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by SkipM4** [hosizoraru/StarVoyager#4]
![Screenshot_2023-05-23-08-20-37-522_com.fankes.apperrorstracking.png](https://github.com/hosizoraru/StarVoyager/assets/40311581/b7a32c19-242d-4b4d-a1ca-94ae157be5a3)

当在模块设置里重启作用域而没有获取到SU权限时，模块直接崩溃
建议handle此错误并提示用户“请授予模块root权限”

**Comment by hosizoraru** [comment]
你是ksu用户吗？magisk用户没有给予root权限或者拒绝权限是不会fc掉App的，只会提示App被拒绝了权限不会fc。
ksu我的mix4没有第三方内核我无法测试，但我可以尝试在下个版本加一下这个日志判断但我无法测试。如果后续仍有问题请继续反馈。

**Comment by hosizoraru** [comment]
我找了一下其他ksu用户测试了一下，目前已经测试好了，将在下一个版本加上。感谢反馈。
