### ISSUE TITLE
Xiaomi Pad 6桌面后台模糊hook失效

### ISSUE THREAD

**Issue by misaka-13766** [hosizoraru/StarVoyager#5]
如题。桌面版本RELEASE-4.40.5745-05151615，系统版本MIUI Pad 14.0.5，附上LSPosed日志，麻烦看下qwq。
[LSPosed_2023-05-27T11_16_13.022144.zip](https://github.com/hosizoraru/StarVoyager/files/11580911/LSPosed_2023-05-27T11_16_13.022144.zip)

**Comment by hosizoraru** [comment]
![IMAGE 2023-05-28 03:47:02](https://github.com/hosizoraru/StarVoyager/assets/63982994/641556b0-14dd-4035-b342-4f6cdff1fff3)
![截屏2023-05-28 03 48 06](https://github.com/hosizoraru/StarVoyager/assets/63982994/e620701f-df53-4d08-8d10-26a21c060940)

我看了一下log，这个8000+行，还有另一个不多的log，我的模块几乎没产生有什么log,也没有error log，8000+行几乎全是cemiuiler,MzFreeForm和miuiextra产生的。其中cemiuiler，miuiextra产生了不少的error log，你应该去那边反馈。主要是我没写过后台模糊hook的功能。。。

**Comment by hosizoraru** [comment]
甚至我的模块只有2行是我的log，建议去找他们反馈
[ 2023-05-27T11:15:19.349    10119: 22741: 22741 I/LSPosed-Bridge  ] Loading module star.sky.voyager from /data/app/~~YAPRV2enDQy8za_dTfOwcA==/star.sky.voyager-xRPzifk8tCWt6aZXBZUNTw==/base.apk
[ 2023-05-27T11:15:19.352    10119: 22741: 22741 I/LSPosed-Bridge  ]   Loading class star.sky.voyager.hook.MainHook
其他和我没关系，所以这不是我的模块问题了

**Comment by misaka-13766** [comment]
好奇怪，抓log的时候已经把cemiuiler关掉了，emmm...可能是没有后台模糊hook的原因吧。总之麻烦啦w

**Comment by misaka-13766** [comment]
其实就是一个很简单的问题，Pad桌面后台模糊没有（即使我开启了解锁设备限制），隔壁cemiuiler是正常的。

可能是我没描述清楚问题，但是既然您也找不到问题，那就完全没修的必要，我还可以继续用西米露，那边完全没问题的，就这样。
