### ISSUE TITLE
系统桌面可以添加快速切换应用吗

### ISSUE THREAD

**Issue by mymine** [hosizoraru/StarVoyager#6]
快速切换应用 从屏幕两侧向内滑动并停顿，快速切换上一个 应用
![Screenshot_2023-05-30-19-52-48-795_com miui home](https://github.com/hosizoraru/StarVoyager/assets/2943365/b5ccd0f8-fbec-4ffb-96c8-f74bdd49a9e4)
桌面APP
(https://www.lanzoui.com/iq9WM0xr4tnc)

**Comment by hosizoraru** [comment]
本来想等写出来后再来告诉你的，不过你已经close了，我就简单回复一下吧。
首先理论上是能写的，但是涉及到的代码量很大，我和其他修改版桌面作者讨论过。而代码量过大意味着我不敢打包票一定短期内给你写出来。未来可能会和别人一起研究怎么写，但我不保证一定会写出来。

**Comment by mymine** [comment]
> 本来想等写出来后再来告诉你的，不过你已经close了，我就简单回复一下吧。 首先理论上是能写的，但是涉及到的代码量很大，我和其他修改版桌面作者讨论过。而代码量过大意味着我不敢打包票一定短期内给你写出来。未来可能会和别人一起研究怎么写，但我不保证一定会写出来。

好的
