### ISSUE TITLE
能不能添加一个锁屏状态下唤醒屏幕（点亮一次屏幕），刷新一次下面的充电信息

### ISSUE THREAD

**Issue by yinzhefuyun** [hosizoraru/StarVoyager#8]
能不能添加一个锁屏状态下唤醒屏幕，刷新一次下面的充电信息，我观察了一下，下面的刷新好像是电流变化（例如30%充电到31%这样数字变化了才刷新一次），能不能加一个屏幕唤醒也刷新一次下面的充电功耗信息
我就查项目代码查到和这个有关com.android.keyguard.charge.ChargeUtils，不知道要怎么改

**Comment by hosizoraru** [comment]
最新ci已经优化了刷新频率且可以自定义了
当息屏的时候不会刷新，亮屏的刷新频率可以自定义，单位为0.1s
